"""Domain models for Epics.

These are *application-level* contracts shared by the EpicAgent, the LangGraph
workflow, the JiraService, and reporting. They are intentionally free of any
SDK, transport, or framework dependency (no Anthropic, Jira SDK, FastAPI, or
LangGraph imports) so the same vocabulary flows unchanged across every layer.

The module contains contracts only — no business, service, or workflow logic.
Validators here enforce *data integrity* (non-blank text, non-empty required
collections, no duplicates, consistent timestamps), not domain behaviour.

An Epic references its child stories only by opaque identifier
(``related_story_ids``), never by importing the story model, so the two schemas
stay decoupled. The base model and helper validators are deliberately generic
so future roadmap models can reuse the same conventions.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import Field, computed_field, field_validator, model_validator

from src.schemas.base import (
    DomainModel as _DomainModel,
    clean_unique_tokens as _clean_unique_tokens,
    require_non_blank as _require_non_blank,
)


# --------------------------------------------------------------------------- #
# Enumerations
# --------------------------------------------------------------------------- #
class EpicPriority(str, Enum):
    """Relative priority of an epic (aligned with common Jira priorities)."""

    LOWEST = "lowest"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    HIGHEST = "highest"


class EpicStatus(str, Enum):
    """Lifecycle state of an epic as it moves toward and through delivery.

    ``DRAFT`` — freshly generated by an agent.
    ``PROPOSED`` — surfaced for human review.
    ``APPROVED`` / ``REJECTED`` — outcome of the human-approval gate.
    ``CREATED`` — materialized as a Jira epic.
    ``IN_PROGRESS`` — actively being delivered.
    ``DONE`` — completed.
    """

    DRAFT = "draft"
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    CREATED = "created"
    IN_PROGRESS = "in_progress"
    DONE = "done"


# --------------------------------------------------------------------------- #
# Value objects
# --------------------------------------------------------------------------- #
class EpicGoal(_DomainModel):
    """A single, measurable success goal for an epic.

    ``description`` states the goal; the optional ``metric``/``target`` pair
    records how it is measured and the value that denotes success.
    """

    description: str = Field(min_length=1, description="What the goal is, in plain language.")
    metric: str | None = Field(
        default=None, description="How the goal is measured, e.g. 'activation rate'."
    )
    target: str | None = Field(
        default=None, description="Target value denoting success, e.g. '>= 20%'."
    )

    @field_validator("description")
    @classmethod
    def _description_not_blank(cls, value: str) -> str:
        """Goal description cannot be blank."""
        return _require_non_blank(value, field="description")


# --------------------------------------------------------------------------- #
# Aggregate models
# --------------------------------------------------------------------------- #
class Epic(_DomainModel):
    """A large body of work that groups related user stories toward an objective.

    ``id`` is optional because an epic is drafted before it is assigned any
    identifier (local or Jira). ``owner``, ``target_release``, ``created_at``,
    and ``updated_at`` are optional because they are frequently unknown at
    generation time.
    """

    id: str | None = Field(default=None, description="Optional epic identifier.")
    title: str = Field(min_length=1, max_length=255, description="Short epic title.")
    summary: str = Field(min_length=1, description="Concise summary of the epic.")
    business_value: str = Field(
        min_length=1, description="Why the epic matters to the business."
    )
    objective: str = Field(min_length=1, description="The primary outcome the epic pursues.")
    success_metrics: tuple[EpicGoal, ...] = Field(
        min_length=1, description="At least one measurable success goal."
    )
    owner: str | None = Field(
        default=None, description="Optional owner (account id or name)."
    )
    priority: EpicPriority = Field(
        default=EpicPriority.MEDIUM, description="Relative priority of the epic."
    )
    status: EpicStatus = Field(
        default=EpicStatus.DRAFT, description="Lifecycle state of the epic."
    )
    labels: tuple[str, ...] = Field(
        default=(), description="Free-form labels; unique and non-blank."
    )
    related_story_ids: tuple[str, ...] = Field(
        min_length=1,
        description="Identifiers of stories under this epic; at least one, unique.",
    )
    target_release: str | None = Field(
        default=None, description="Optional target release or version, e.g. '2026-Q3'."
    )
    created_at: datetime | None = Field(
        default=None, description="Optional creation timestamp."
    )
    updated_at: datetime | None = Field(
        default=None, description="Optional last-update timestamp."
    )

    @field_validator("title", "summary", "business_value", "objective")
    @classmethod
    def _text_fields_not_blank(cls, value: str, info) -> str:  # type: ignore[no-untyped-def]
        """Core narrative fields cannot be blank."""
        return _require_non_blank(value, field=info.field_name)

    @field_validator("labels")
    @classmethod
    def _labels_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Labels must be unique and non-blank."""
        return _clean_unique_tokens(value, field="labels")

    @field_validator("related_story_ids")
    @classmethod
    def _related_story_ids_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Related story identifiers must be unique and non-blank."""
        return _clean_unique_tokens(value, field="related_story_ids")

    @model_validator(mode="after")
    def _timestamps_consistent(self) -> "Epic":
        """When both timestamps are present, updated_at cannot precede created_at."""
        if (
            self.created_at is not None
            and self.updated_at is not None
            and self.updated_at < self.created_at
        ):
            raise ValueError("updated_at must not be earlier than created_at")
        return self


class EpicCollection(_DomainModel):
    """An ordered set of epics, e.g. a slice of a product roadmap."""

    epics: tuple[Epic, ...] = Field(default=(), description="The epics in this collection.")
    roadmap_id: str | None = Field(
        default=None, description="Optional identifier of the source roadmap."
    )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def count(self) -> int:
        """Number of epics in the collection."""
        return len(self.epics)

    @model_validator(mode="after")
    def _unique_epic_ids(self) -> "EpicCollection":
        """Epic identifiers, when present, must be unique within the collection."""
        ids = [epic.id for epic in self.epics if epic.id is not None]
        if len(set(ids)) != len(ids):
            raise ValueError("epic identifiers must be unique within a collection")
        return self
