"""Domain models for AI-generated agile user stories.

These are *application-level* contracts shared by the RequirementAgent, the
StoryAgent, the LangGraph workflow, and the JiraService. They are intentionally
free of any SDK, transport, or framework dependency (no Anthropic, Jira SDK,
FastAPI, or LangGraph imports) so the same vocabulary flows unchanged across
every layer.

The module contains contracts only — no business logic, service logic, or
workflow orchestration. Validators here enforce *data integrity* (non-blank
text, non-empty criteria, no duplicates), not domain behaviour.

The base model and helper validators are deliberately generic so that the
forthcoming ``epic.py`` and ``task.py`` schemas can reuse the same conventions
(immutability, unknown-field rejection, priority/label/dependency handling).
"""

from __future__ import annotations

from enum import Enum
from typing import Iterable

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator, model_validator


# --------------------------------------------------------------------------- #
# Shared base + reusable validators
# --------------------------------------------------------------------------- #
class _DomainModel(BaseModel):
    """Base for every story domain contract.

    All models are immutable (``frozen``) and reject unknown fields
    (``extra="forbid"``), so a contract mismatch fails loudly rather than
    silently carrying untyped data through the application. Reusable by future
    Epic/Task models via subclassing.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")


def _require_non_blank(value: str, *, field: str) -> str:
    """Return the trimmed value, raising when it is empty or whitespace-only."""
    cleaned = value.strip()
    if not cleaned:
        raise ValueError(f"{field} must not be blank")
    return cleaned


def _clean_unique_tokens(values: Iterable[str], *, field: str) -> tuple[str, ...]:
    """Trim string tokens and reject blanks and duplicates, preserving order."""
    cleaned = tuple(value.strip() for value in values)
    if any(not value for value in cleaned):
        raise ValueError(f"{field} must not contain blank entries")
    if len(set(cleaned)) != len(cleaned):
        raise ValueError(f"{field} must not contain duplicate entries")
    return cleaned


# --------------------------------------------------------------------------- #
# Enumerations
# --------------------------------------------------------------------------- #
class StoryPriority(str, Enum):
    """Relative priority of a user story (aligned with common Jira priorities)."""

    LOWEST = "lowest"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    HIGHEST = "highest"


class StoryStatus(str, Enum):
    """Lifecycle state of a story as it moves toward Jira creation.

    ``DRAFT`` — freshly generated by an agent.
    ``PROPOSED`` — surfaced for human review.
    ``APPROVED`` / ``REJECTED`` — outcome of the human-approval gate.
    ``CREATED`` — materialized as a Jira issue.
    """

    DRAFT = "draft"
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    CREATED = "created"


# --------------------------------------------------------------------------- #
# Value objects
# --------------------------------------------------------------------------- #
class AcceptanceCriterion(_DomainModel):
    """A single, testable acceptance criterion for a user story."""

    text: str = Field(min_length=1, description="A single, verifiable acceptance statement.")
    id: str | None = Field(
        default=None, description="Optional stable identifier for the criterion."
    )

    @field_validator("text")
    @classmethod
    def _text_not_blank(cls, value: str) -> str:
        """Acceptance criterion text cannot be blank."""
        return _require_non_blank(value, field="text")


# --------------------------------------------------------------------------- #
# Aggregate models
# --------------------------------------------------------------------------- #
class UserStory(_DomainModel):
    """An agile user story: 'As a <persona>, I want <goal>, so that <benefit>'.

    ``id`` is optional because a story is generated before it is assigned any
    identifier (local or Jira). ``estimate`` is optional because stories are
    frequently drafted before estimation.
    """

    id: str | None = Field(default=None, description="Optional story identifier.")
    title: str = Field(min_length=1, max_length=255, description="Short story title.")
    description: str = Field(min_length=1, description="Full narrative description of the story.")
    persona: str = Field(min_length=1, description="The 'As a <persona>' role.")
    goal: str = Field(min_length=1, description="The 'I want <goal>' capability.")
    benefit: str = Field(min_length=1, description="The 'so that <benefit>' value.")
    acceptance_criteria: tuple[AcceptanceCriterion, ...] = Field(
        min_length=1, description="At least one testable acceptance criterion."
    )
    priority: StoryPriority = Field(
        default=StoryPriority.MEDIUM, description="Relative priority of the story."
    )
    estimate: float | None = Field(
        default=None, gt=0, description="Optional effort estimate (e.g. story points)."
    )
    labels: tuple[str, ...] = Field(
        default=(), description="Free-form labels; unique and non-blank."
    )
    dependencies: tuple[str, ...] = Field(
        default=(), description="Identifiers of stories this one depends on; unique."
    )
    status: StoryStatus = Field(
        default=StoryStatus.DRAFT, description="Lifecycle state of the story."
    )

    @field_validator("title", "description", "persona", "goal", "benefit")
    @classmethod
    def _text_fields_not_blank(cls, value: str, info) -> str:  # type: ignore[no-untyped-def]
        """Core narrative fields cannot be blank."""
        return _require_non_blank(value, field=info.field_name)

    @field_validator("labels")
    @classmethod
    def _labels_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Labels must be unique and non-blank."""
        return _clean_unique_tokens(value, field="labels")

    @field_validator("dependencies")
    @classmethod
    def _dependencies_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Dependencies must be unique and non-blank."""
        return _clean_unique_tokens(value, field="dependencies")

    @model_validator(mode="after")
    def _no_self_dependency(self) -> "UserStory":
        """A story cannot depend on itself."""
        if self.id is not None and self.id in self.dependencies:
            raise ValueError("a story cannot list itself as a dependency")
        return self


class StoryCollection(_DomainModel):
    """An ordered set of user stories, typically the output of the StoryAgent."""

    stories: tuple[UserStory, ...] = Field(
        default=(), description="The user stories in this collection."
    )
    requirement_id: str | None = Field(
        default=None, description="Optional identifier of the source requirement."
    )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def count(self) -> int:
        """Number of stories in the collection."""
        return len(self.stories)

    @model_validator(mode="after")
    def _unique_story_ids(self) -> "StoryCollection":
        """Story identifiers, when present, must be unique within the collection."""
        ids = [story.id for story in self.stories if story.id is not None]
        if len(set(ids)) != len(ids):
            raise ValueError("story identifiers must be unique within a collection")
        return self
