"""Domain models for implementation tasks.

These are *application-level* contracts shared by the future TaskAgent, the
LangGraph workflow, the JiraService, and reporting. They are intentionally free
of any SDK, transport, or framework dependency (no Anthropic, Jira SDK, FastAPI,
or LangGraph imports) so the same vocabulary flows unchanged across every layer.

The module contains contracts only — no business, service, or workflow logic.
Validators here enforce *data integrity* (non-blank text, no duplicates, no
self-dependency, positive estimate, consistent timestamps), not domain
behaviour.

A Task references its parent story only by opaque identifier
(``parent_story_id``), never by importing the story model, so the two schemas
stay decoupled. The base model and helper validators mirror the conventions in
``story.py`` and ``epic.py`` and are candidates for later consolidation into a
shared ``schemas/base`` module.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import Field, computed_field, field_validator, model_validator

from src.schemas.base import (
    DomainModel as _DomainModel,
    clean_unique_tokens as _clean_unique_tokens,
    require_non_blank as _require_non_blank,
)


# --------------------------------------------------------------------------- #
# Enumerations
# --------------------------------------------------------------------------- #
class TaskPriority(str, Enum):
    """Relative priority of a task (aligned with common Jira priorities)."""

    LOWEST = "lowest"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    HIGHEST = "highest"


class TaskStatus(str, Enum):
    """Lifecycle state of an implementation task.

    ``DRAFT`` — freshly generated by an agent.
    ``PROPOSED`` — surfaced for human review.
    ``APPROVED`` / ``REJECTED`` — outcome of the human-approval gate.
    ``CREATED`` — materialized as a Jira issue.
    ``IN_PROGRESS`` — actively being worked on.
    ``BLOCKED`` — cannot progress until a dependency is resolved.
    ``DONE`` — completed.
    """

    DRAFT = "draft"
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    CREATED = "created"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    DONE = "done"


class TaskType(str, Enum):
    """The nature of an implementation task."""

    FEATURE = "feature"
    BUG = "bug"
    CHORE = "chore"
    SPIKE = "spike"
    TEST = "test"
    DOCUMENTATION = "documentation"
    REFACTOR = "refactor"


# --------------------------------------------------------------------------- #
# Aggregate models
# --------------------------------------------------------------------------- #
class Task(_DomainModel):
    """A concrete unit of implementation work derived from a user story.

    ``id`` is optional because a task is generated before it is assigned any
    identifier (local or Jira). ``estimate``, ``assignee``, ``created_at``, and
    ``updated_at`` are optional because they are frequently unknown at
    generation time.
    """

    id: str | None = Field(default=None, description="Optional task identifier.")
    title: str = Field(min_length=1, max_length=255, description="Short task title.")
    description: str = Field(min_length=1, description="Full description of the work to do.")
    parent_story_id: str = Field(
        min_length=1, description="Identifier of the story this task implements."
    )
    task_type: TaskType = Field(
        default=TaskType.FEATURE, description="The nature of the task."
    )
    priority: TaskPriority = Field(
        default=TaskPriority.MEDIUM, description="Relative priority of the task."
    )
    status: TaskStatus = Field(
        default=TaskStatus.DRAFT, description="Lifecycle state of the task."
    )
    estimate: float | None = Field(
        default=None, gt=0, description="Optional effort estimate (e.g. hours or points)."
    )
    assignee: str | None = Field(
        default=None, description="Optional assignee (account id or name)."
    )
    labels: tuple[str, ...] = Field(
        default=(), description="Free-form labels; unique and non-blank."
    )
    dependencies: tuple[str, ...] = Field(
        default=(), description="Identifiers of tasks this one depends on; unique."
    )
    created_at: datetime | None = Field(
        default=None, description="Optional creation timestamp."
    )
    updated_at: datetime | None = Field(
        default=None, description="Optional last-update timestamp."
    )

    @field_validator("title", "description", "parent_story_id")
    @classmethod
    def _text_fields_not_blank(cls, value: str, info) -> str:  # type: ignore[no-untyped-def]
        """Required text fields cannot be blank."""
        return _require_non_blank(value, field=info.field_name)

    @field_validator("labels")
    @classmethod
    def _labels_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Labels must be unique and non-blank."""
        return _clean_unique_tokens(value, field="labels")

    @field_validator("dependencies")
    @classmethod
    def _dependencies_unique(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Dependencies must be unique and non-blank."""
        return _clean_unique_tokens(value, field="dependencies")

    @model_validator(mode="after")
    def _no_self_dependency(self) -> "Task":
        """A task cannot depend on itself."""
        if self.id is not None and self.id in self.dependencies:
            raise ValueError("a task cannot list itself as a dependency")
        return self

    @model_validator(mode="after")
    def _timestamps_consistent(self) -> "Task":
        """When both timestamps are present, updated_at cannot precede created_at."""
        if (
            self.created_at is not None
            and self.updated_at is not None
            and self.updated_at < self.created_at
        ):
            raise ValueError("updated_at must not be earlier than created_at")
        return self


class TaskCollection(_DomainModel):
    """An ordered set of tasks, typically the output of the TaskAgent."""

    tasks: tuple[Task, ...] = Field(default=(), description="The tasks in this collection.")
    parent_story_id: str | None = Field(
        default=None, description="Optional identifier of the story these tasks belong to."
    )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def count(self) -> int:
        """Number of tasks in the collection."""
        return len(self.tasks)

    @model_validator(mode="after")
    def _unique_task_ids(self) -> "TaskCollection":
        """Task identifiers, when present, must be unique within the collection."""
        ids = [task.id for task in self.tasks if task.id is not None]
        if len(set(ids)) != len(ids):
            raise ValueError("task identifiers must be unique within a collection")
        return self
